* Pipeline
* Pipelines chains together multiple steps so that output of each step is used
* as input to the next step.
* Pipelines makes it easy to apply the same preprocessing to train and test!

## without pipelines:


In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder 
from sklearn.preprocessing import minmax_scale
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score


In [ ]:
df = pd.read_csv(r'Titanic-Dataset.csv')
print(df.head())
df = df.drop(columns=['PassengerId', 'Name','Ticket','Cabin'])
print(df.head())


   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
  

In [6]:

x_train, x_test, y_train, y_test = train_test_split(df.drop(columns='Survived'), df['Survived'], test_size= .2)
print(x_train.shape)

# print(df.isnull().sum())            #age = 177 numm value


(712, 7)


In [7]:

# SimpuleImputer:  Embarked, Age
si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')


In [8]:

x_train_age = si_age.fit_transform(x_train[['Age']])
x_train_embarked = si_embarked.fit_transform(x_train[['Embarked']])
 
x_test_age = si_age.transform(x_test[['Age']])
x_test_embarked = si_embarked.transform(x_test[['Embarked']])

# print(x_train_age)

In [9]:

# OneHotEncoder Age and Embarked
hot_sex = OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore')
hot_embarked = OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore')


In [10]:

x_train_sex= hot_sex.fit_transform(x_train[['Sex']])
x_test_sex= hot_sex.transform(x_test[['Sex']])


In [11]:

x_train_embarked= hot_embarked.fit_transform(x_train_embarked)
x_test_embarked= hot_embarked.transform(x_test_embarked)
# print(x_test_embarked)
# print(x_test_sex)


In [12]:

x_train_rem = x_train.drop(columns=['Sex','Age','Embarked'])
x_test_rem = x_test.drop(columns=['Sex','Age','Embarked'])
# print(x_train_rem)
x_train_trantransform= np.concatenate((x_train_rem, x_train_age, x_train_sex, x_train_embarked), axis=1)
x_test_trantransform= np.concatenate((x_test_rem, x_test_age, x_test_sex, x_test_embarked), axis=1)
print(x_train_trantransform)


[[2. 0. 0. ... 1. 0. 1.]
 [1. 0. 0. ... 1. 0. 1.]
 [3. 1. 1. ... 1. 0. 1.]
 ...
 [3. 0. 0. ... 1. 0. 1.]
 [3. 0. 0. ... 1. 0. 1.]
 [1. 1. 0. ... 0. 0. 1.]]


In [13]:

# Training model
clf = DecisionTreeClassifier()
clf.fit(x_train_trantransform, y_train)
y_pred = clf.predict(x_test_trantransform)
print(y_pred)


[1 1 0 1 0 0 0 1 1 1 0 0 1 0 1 0 1 0 1 0 0 1 0 0 1 1 1 0 0 0 0 1 1 0 0 0 1
 1 1 1 0 1 0 0 1 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 1 1
 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 1 1 0 1 0 0 1 1 0 0 0 1 0 1 0
 0 1 1 0 1 0 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0
 0 1 1 0 0 0 0 0 0 1 0 0 1 0 1 1 0 1 0 1 1 0 0 0 0 0 0 1 0 0 1]


In [14]:

print(accuracy_score(y_test, y_pred)*100)


81.56424581005587


In [17]:

import pickle
import os

# * os.makedirs('models', exist_ok=True)
# * pickle.dump(hot_sex, open('models/hot_sex.pkl', 'wb'))
# * pickle.dump(hot_embarked, open('models/hot_embarked.pkl', 'wb'))
# * pickle.dump(clf, open('models/clf.pkl', 'wb'))
