## Categorical data: Nominal(No order) , Ordinal (with order)

## Make seperate columns for a perticular column to represent all feachers of that column
* Ex:
* Original Color	Color_Red	Color_Blue	Color_Green
### Red	    1	0	0
### Blue	    0	1	0
### Green	    0	0	1

### Note: If there are 50 different itemns in a column then we'll make 50 columns




In [30]:
#* Dummy Variable trap
# we can remove any one colum from n columns (Multicollinearity)
import pandas as pd
import numpy as np


In [ ]:
data = pd.read_csv(r'cars.csv')
print(data.sample(10))


           brand  km_driven    fuel         owner  selling_price
4414      Jaguar       9000  Diesel   First Owner        2711000
450      Hyundai      25000  Petrol   First Owner         800000
188     Mahindra      15000  Petrol  Second Owner         450000
6010        Tata      42000  Diesel  Second Owner         390000
3740    Mahindra     100000  Diesel  Second Owner         360000
1545      Maruti      20000  Petrol   First Owner         700000
7363       Honda      18300  Petrol   First Owner         890000
579     Mahindra      80000  Diesel  Second Owner         605000
979   Volkswagen      80000  Diesel   Third Owner         350000
7813    Mahindra      95000  Diesel  Second Owner         450000


In [32]:

# print(data['brand'].value_counts())
print(data['brand'].nunique())
print(data['fuel'].value_counts())
print(data['owner'].value_counts())


32
fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64
owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64


In [33]:

# 1. HotOneEncoding by using Pandas
data1 = pd.get_dummies(data=data, columns= ['owner', 'fuel'])


In [39]:

# print(data1, data1.shape)   #(8128,12)
#  Dummy Variable trap
data2 = pd.get_dummies(data=data, columns= ['owner', 'fuel'], drop_first=True)
# print(data2.shape)      # from both columns one one columns reduced (8128,10)
print(data2.head(10))


     brand  km_driven  selling_price  owner_Fourth & Above Owner  \
0   Maruti     145500         450000                       False   
1    Skoda     120000         370000                       False   
2    Honda     140000         158000                       False   
3  Hyundai     127000         225000                       False   
4   Maruti     120000         130000                       False   
5  Hyundai      45000         440000                       False   
6   Maruti     175000          96000                       False   
7   Maruti       5000          45000                       False   
8   Toyota      90000         350000                       False   
9     Ford     169000         200000                       False   

   owner_Second Owner  owner_Test Drive Car  owner_Third Owner  fuel_Diesel  \
0               False                 False              False         True   
1                True                 False              False         True   
2             

In [35]:
# OneHotEncoding using Sklean 
from sklearn.model_selection import train_test_split
x_train, x_test, Y_train, y_text = train_test_split(data.iloc[:,0:4], data.iloc[:,-1] ,test_size=.2)
print(x_train.head())


           brand  km_driven    fuel         owner
6681        Audi      25000  Diesel  Second Owner
3065  Volkswagen     120000  Diesel  Second Owner
1179      Maruti      40000  Diesel   First Owner
1228      Maruti      72000  Petrol   First Owner
7972      Maruti     108000  Diesel   First Owner


In [37]:

from sklearn.preprocessing import OneHotEncoder
obj = OneHotEncoder(drop='first',sparse_output=False)           # by default produces :Sparse Matrics, use sparse_output= perameter
#print(x_train_new.toarray())            # Sparse matrics produced by OneHotEncoder
x_train_new = obj.fit_transform(x_train[['fuel', 'owner']])
x_test_new = obj.transform(x_test[['fuel', 'owner']])
print(x_train_new)


[[1. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


In [38]:
final_array = np.hstack((x_train[['brand','km_driven']].values, x_train_new))               # work done
print(final_array)


[['Audi' 25000 1.0 ... 1.0 0.0 0.0]
 ['Volkswagen' 120000 1.0 ... 1.0 0.0 0.0]
 ['Maruti' 40000 1.0 ... 0.0 0.0 0.0]
 ...
 ['Maruti' 25000 1.0 ... 0.0 0.0 0.0]
 ['Tata' 50000 0.0 ... 1.0 0.0 0.0]
 ['Maruti' 25000 0.0 ... 0.0 0.0 0.0]]


In [29]:

# Creating final dataframe

final_column = ['brand', 'km_driven'] + list( obj.get_feature_names_out(['fuel', 'owner']))
d = pd.DataFrame(final_array, columns= final_column)
print(d.head())


           brand km_driven fuel_Diesel fuel_LPG fuel_Petrol  \
0  Mercedes-Benz     23000         0.0      0.0         0.0   
1         Maruti    180000         0.0      0.0         1.0   
2           Tata    225000         0.0      0.0         1.0   
3         Maruti    120000         0.0      0.0         1.0   
4         Maruti    120000         1.0      0.0         0.0   

  owner_Fourth & Above Owner owner_Second Owner owner_Test Drive Car  \
0                        0.0                0.0                  0.0   
1                        0.0                0.0                  0.0   
2                        0.0                0.0                  0.0   
3                        0.0                1.0                  0.0   
4                        0.0                0.0                  0.0   

  owner_Third Owner  
0               0.0  
1               0.0  
2               0.0  
3               0.0  
4               0.0  
